name: Fetch By Pattern

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  fetch-combinations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - women: "true"
            filter_by: "patterns"
          - women: "false"
            filter_by: "patterns"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Display Matrix Combination
        run: |
          echo "Running with configuration:"
          echo "WOMEN: ${{ matrix.women }}"
          echo "FILTER_BY: ${{ matrix.filter_by }}"
          echo "ONLY_VINTAGE: false"

      - name: Build Docker Image
        run: docker build -t fetch .

      - name: Run Docker Container
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
        run: docker run -e SECRETS_JSON -e WOMEN=${{ matrix.women }} -e ONLY_VINTAGE=false -e FILTER_BY=${{ matrix.filter_by }} fetch 